# advection_multi

model: lod # fno // lod


#['1D_Advection_Sols_beta0.1.hdf5', '1D_Advection_Sols_beta0.2.hdf5', \
#'1D_Advection_Sols_beta0.4.hdf5', '1D_Advection_Sols_beta0.7.hdf5', \
#'1D_Advection_Sols_beta1.0.hdf5', '1D_Advection_Sols_beta2.0.hdf5', \
#'1D_Advection_Sols_beta4.0.hdf5', '1D_Advection_Sols_beta7.0.hdf5']

dataset:
    name: Advection
    file_names: ["1D_Advection_Sols_beta0.1.hdf5", "1D_Advection_Sols_beta0.2.hdf5", 
                  "1D_Advection_Sols_beta0.4.hdf5", "1D_Advection_Sols_beta0.7.hdf5", 
                  "1D_Advection_Sols_beta1.0.hdf5", "1D_Advection_Sols_beta2.0.hdf5",
                  "1D_Advection_Sols_beta4.0.hdf5", "1D_Advection_Sols_beta7.0.hdf5"]
    t_train: 41
    x_range: 256
    initial_step: 10
    reduced_resolution: 4
    reduced_resolution_t: 5
    reduced_batch: 1
    num_channels: 1

pod_parameter:
    N_eigen: 64

training:
    random_seed: 3407
    num_workers: 8
    batch_size: 64
    epochs: 500
    learning_rate: 1.e-3

fno:
    modes: 12
    width: 20