# burgers.yaml

model: lod # fno // lod-small // lod

#['1D_Burgers_Sols_Nu0.001.hdf5', '1D_Burgers_Sols_Nu0.002.hdf5', '1D_Burgers_Sols_Nu0.004.hdf5', \
#'1D_Burgers_Sols_Nu0.01.hdf5', '1D_Burgers_Sols_Nu0.02.hdf5', '1D_Burgers_Sols_Nu0.04.hdf5', \
#'1D_Burgers_Sols_Nu0.1.hdf5', '1D_Burgers_Sols_Nu0.2.hdf5', '1D_Burgers_Sols_Nu0.4.hdf5', \
#'1D_Burgers_Sols_Nu1.0.hdf5', '1D_Burgers_Sols_Nu2.0.hdf5', '1D_Burgers_Sols_Nu4.0.hdf5']

dataset:
    name: Burgers
    file_names: ["1D_Burgers_Sols_Nu4.0.hdf5"]
    t_train: 41
    x_range: 256
    initial_step: 10
    reduced_resolution: 4
    reduced_resolution_t: 5
    reduced_batch: 1
    num_channels: 1

pod_parameter:
    N_eigen: 64

training:
    random_seed: 3407
    num_workers: 8
    batch_size: 64
    epochs: 500
    learning_rate: 1.e-3

fno:
    modes: 12
    width: 20