# shallow-water.yaml

model: lod-small # fno // lod-small // lod

dataset:
    name: shallow-water
    file_names: ['2D_rdb_NA_NA.h5']
    t_train: 101
    x_range: 128
    initial_step: 10
    reduced_resolution: 1
    reduced_resolution_t: 1
    reduced_batch: 1
    num_channels: 1

pod_parameter:
    N_eigen: 64

training:
    random_seed: 3407
    num_workers: 8
    batch_size: 8
    epochs: 500
    learning_rate: 1.e-3

fno:
    modes: 12
    width: 20